name: weather
description: "A Flutter Weather App"
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0

cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/clouds.png
   - assets/thunderstorm.jpg
   - assets/drizzle.jpg
   - assets/default.png
   - assets/partly_cloudy.jpg
   - assets/rain.jpg
   - assets/snow.jpg